
uses = {
    "Alpinia Galanga (Rasna)": "Anti-inflammatory, analgesic, digestive aid, respiratory support, immune system booster, joint health.",
    "Amaranthus Viridis (Arive-Dantu)": "Nutritional benefits, potential medicinal properties, anti-inflammatory effects, antioxidant support, digestive aid.",
    "Artocarpus Heterophyllus (Jackfruit)": "High nutritional content, potential anti-inflammatory properties, digestive aid, immune system booster, cardiovascular support.",
    "Azadirachta Indica (Neem)": "Antibacterial, antifungal, anti-inflammatory, skincare, immune system support, digestive aid.",
    "Basella Alba (Basale)": "Nutritional benefits, potential medicinal properties, anti-inflammatory effects, digestive aid, cardiovascular support, respiratory health.",
    "Brassica Juncea (Indian Mustard)": "Rich in nutrients, potential anti-inflammatory, antioxidant properties, respiratory support, digestive aid, joint health.",
    "Carissa Carandas (Karanda)": "Potential anti-inflammatory, antioxidant effects, digestive aid, skincare, immune system support, respiratory health.",
    "Citrus Limon (Lemon)": "High vitamin C content, immune-boosting, traditional remedies, digestive aid, skincare, respiratory health.",
    "Ficus Auriculata (Roxburgh fig)": "Traditional medicine, potential anti-inflammatory effects, digestive aid, respiratory support, joint health.",
    "Ficus Religiosa (Peepal Tree)": "Potential anti-inflammatory, antioxidant properties, traditional remedies, respiratory support, skincare, immune system support.",
    "Hibiscus Rosa-sinensis": "Hair and skin health, traditional medicine, digestive aid, respiratory support, immune system support.",
    "Jasminum (Jasmine)": "Traditional medicine, potential calming, anti-inflammatory effects, skincare, respiratory support, digestive aid.",
    "Mangifera Indica (Mango)": "Nutritional benefits, digestive health, antioxidant properties, anti-inflammatory effects, immune system support, skincare, cardiovascular support.",
    "Mentha (Mint)": "Digestive, respiratory benefits, traditional remedies, calming effects, skincare, immune system support.",
    "Moringa Oleifera (Drumstick)": "High nutritional content, potential anti-inflammatory properties, traditional remedies, immune system support, cardiovascular support, digestive aid, joint health.",
    "Muntingia Calabura (Jamaica Cherry-Gasagase)": "Potential anti-inflammatory, antioxidant effects, traditional medicine, digestive aid, skincare, respiratory health, immune system support.",
    "Murraya Koenigii (Curry)": "Traditional medicine, potential digestive, anti-inflammatory properties, respiratory support, skincare, joint health.",
    "Nerium Oleander (Oleander)": "Caution: Highly toxic, not recommended for medicinal use.",
    "Nyctanthes Arbor-tristis (Parijata)": "Traditional medicine, potential anti-inflammatory, antipyretic effects, respiratory support, skincare, digestive aid.",
    "Ocimum Tenuiflorum (Tulsi)": "Sacred, traditional medicine, potential immune-boosting, anti-inflammatory effects, respiratory support, digestive aid, skincare.",
    "Piper Betle (Betel)": "Traditional medicine, potential digestive, antimicrobial properties, respiratory support, skincare, immune system support.",
    "Plectranthus Amboinicus (Mexican Mint)": "Potential anti-inflammatory, antimicrobial effects, traditional medicine, respiratory support, digestive aid, skincare.",
    "Pongamia Pinnata (Indian Beech)": "Used in preparation of crude drugs for the treatment of tumors, piles, skin diseases, and ulcers",
    "Psidium Guajava (Guava)": "High vitamin C content, digestive benefits, traditional remedies, skincare, immune system support, respiratory health.",
    "Punica Granatum (Pomegranate)": "Rich in antioxidants, potential anti-inflammatory, cardiovascular benefits, skincare, immune system support, digestive aid.",
    "Santalum Album (Sandalwood)": "Potential anti-inflammatory, antimicrobial properties, traditional medicine, skincare, respiratory support, immune system support.",
    "Syzygium Cumini (Jamun)": "Traditional medicine, potential anti-diabetic, anti-inflammatory effects, respiratory support, skincare, digestive aid.",
    "Syzygium Jambos (Rose Apple)": "Potential anti-inflammatory, digestive benefits, traditional medicine, skincare, respiratory support, immune system support.",
    "Tabernaemontana Divaricata (Crape Jasmine)": "Traditional medicine, potential anti-inflammatory, analgesic effects, skincare, respiratory support, digestive aid.",
    "Trigonella Foenum-graecum (Fenugreek)": "Potential digestive, anti-inflammatory properties, traditional medicine, respiratory support, skincare, joint health.",
    "arjun_diseased": "Cardiovascular benefits, potential anti-inflammatory properties.",
    "arjun_healthy": "Cardiovascular benefits, potential anti-inflammatory properties.",
    "bael_diseased": "Digestive benefits, traditional medicine.",
    "basil_healthy": "Traditional medicine, potential anti-inflammatory, antimicrobial properties.",
    "chinar_diseased": "Used in folk medicine against tooth and knee pain, wounds, inflammation, and stomach discomfort",
    "chinar_healthy": "Used in folk medicine against tooth and knee pain, wounds, inflammation, and stomach discomfort",
    "guava_diseased": "High vitamin C content, digestive benefits, traditional remedies.",
    "guava_healthy": "High vitamin C content, digestive benefits, traditional remedies.",
    "jamun_diseased": "Traditional medicine, potential anti-diabetic, anti-inflammatory effects.",
    "jamun_healthy": "Traditional medicine, potential anti-diabetic, anti-inflammatory effects.",
    "jatropha_diseased": "Potential uses being studied include anti-inflammatory and analgesic properties.",
    "jatropha_healthy": "used to treat bacterial and fungal infections, muscle pain, jaundice, obtaining new drugs through the identification of active ingredients to eliminate pathogens or inhibit signs and symptoms of human and veterinary diseases.",
    "lemon_diseased": "High vitamin C content, immune-boosting, traditional remedies.",
    "lemon_healthy": "High vitamin C content, immune-boosting, traditional remedies.",
    "mango_diseased": "Nutritional benefits, digestive health, antioxidant properties, anti-inflammatory effects, immune system support.",
    "mango_healthy": "Nutritional benefits, digestive health, antioxidant properties, anti-inflammatory effects, immune system support.",
    "pomegranate_diseased": "Rich in antioxidants, potential anti-inflammatory, cardiovascular benefits.",
    "pomegranate_healthy": "Rich in antioxidants, potential anti-inflammatory, cardiovascular benefits.",
    "pongamia_pinnata_diseased": "Used in preparation of crude drugs for the treatment of tumors, piles, skin diseases, and ulcers",
    "pongamia_pinnata_healthy": "Used in preparation of crude drugs for the treatment of tumors, piles, skin diseases, and ulcers"
}
